name: test_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# State managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

# Http requests
  http: ^1.0.0

# Code generation
  build_runner: ^2.4.4
  freezed: ^2.3.5
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Code generation
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
